version: '3'

services:
  db:
    image: mariadb
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  apache:
    build: ./apache
    volumes:
      - ./apache:/var/www/html/public
    ports:
      - 8080:80
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
    - ./nginx:/var/www/html
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 8079:80



  